# GABOR

In [2]:
from skimage.feature import hog
from skimage.feature import local_binary_pattern
import cv2 
import os
from sklearn import svm
from sklearn import metrics
import numpy as np
import time
from sklearn.metrics import confusion_matrix
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import precision_score
from sklearn import metrics
import numpy as np 
import matplotlib.pyplot as plt
import glob
import seaborn as sns
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier
import joblib

In [3]:
# GABOR KERNEL
def gabor(folder_name, suf_path, eqhist=True):
    i=0
    currentframe =1
    for filename in os.listdir(folder_name):
        #path
        path=os.path.join(folder_name,filename)
        a=cv2.imread(path)
        
        a = cv2.cvtColor(a, cv2.COLOR_BGR2GRAY)
        
        if eqhist:
            a = cv2.equalizeHist(a)
        a = cv2.resize(a, (300,300))
        
        for ang in range(1,2):
            ksize = 3  #Use size that makes sense to the image and fetaure size. Large may not be good. 
            #On the synthetic image it is clear how ksize affects imgae (try 5 and 50)
            sigma = 2 #Large sigma on small features will fully miss the features. 
            theta = ang*np.pi/4  #/4 shows horizontal 3/4 shows other horizontal. Try other contributions
            lamda = 1*np.pi /4  #1/4 works best for angled. 
            gamma=0.4  #Value of 1 defines spherical. Calue close to 0 has high aspect ratio
            #Value of 1, spherical may not be ideal as it picks up features from other regions. 
            phi = 0  #Phase offset. 

            kernel = cv2.getGaborKernel((ksize, ksize), sigma, theta, lamda, gamma, phi, ktype=cv2.CV_32F)
            fimg = cv2.filter2D(a, cv2.CV_8UC3, kernel)
            name = "D:\\College\\Third Year\\Computer Vision\\cp2\\Datasets\\Gabor Data\\"+ suf_path + str(currentframe) + '.png'
            print ('Creating...' + name)

            cv2.imwrite(name, fimg)
            currentframe=currentframe+1;
            i=i+1
            if i==3000:
                break;

In [4]:
#Gathering Training Data
gabor(r"D:\College\Third Year\Computer Vision\cp2\Datasets\Common Dataset\Train\Adult", "Train\\Adult\\")

gabor(r"D:\College\Third Year\Computer Vision\cp2\Datasets\Common Dataset\Train\Old", "Train\\Old\\")

gabor(r"D:\College\Third Year\Computer Vision\cp2\Datasets\Common Dataset\Train\Young", "Train\\Young\\")


Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\1.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\2.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\3.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\4.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\5.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\6.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\7.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\8.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\9.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\10.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\11.p

Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\98.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\99.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\100.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\101.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\102.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\103.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\104.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\105.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\106.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\107.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data

Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\189.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\190.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\191.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\192.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\193.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\194.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\195.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\196.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\197.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\198.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Da

Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\283.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\284.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\285.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\286.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\287.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\288.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\289.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\290.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\291.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Adult\292.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Da

Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Old\74.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Old\75.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Old\76.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Old\77.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Old\78.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Old\79.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Old\80.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Old\81.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Old\82.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Old\83.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Old\84.png
Creating..

Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\15.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\16.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\17.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\18.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\19.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\20.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\21.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\22.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\23.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\24.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Y

Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\106.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\107.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\108.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\109.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\110.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\111.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\112.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\113.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\114.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\115.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Da

Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\204.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\205.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\206.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\207.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\208.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\209.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\210.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\211.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\212.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\213.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Da

Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\293.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\294.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\295.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\296.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\297.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\298.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\299.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\300.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\301.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\302.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Da

Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\385.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\386.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\387.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\388.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\389.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\390.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\391.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\392.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\393.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\394.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Da

Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\479.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\480.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\481.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\482.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\483.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\484.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\485.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\486.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\487.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\488.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Da

Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\573.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\574.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\575.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\576.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\577.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\578.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\579.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\580.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\581.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\582.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Da

Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\666.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\667.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\668.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\669.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\670.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\671.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\672.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\673.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\674.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\675.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Da

Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\759.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\760.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\761.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\762.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\763.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\764.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\765.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\766.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\767.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\768.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Da

Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\854.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\855.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\856.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\857.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\858.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\859.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\860.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\861.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\862.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\863.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Da

Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\950.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\951.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\952.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\953.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\954.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\955.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\956.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\957.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\958.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\959.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Da

Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1047.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1048.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1049.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1050.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1051.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1052.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1053.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1054.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1055.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1056.png
Creating...D:\College\Third Year\Computer Vision\cp2\Dataset

Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1139.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1140.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1141.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1142.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1143.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1144.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1145.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1146.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1147.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1148.png
Creating...D:\College\Third Year\Computer Vision\cp2\Dataset

Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1230.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1231.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1232.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1233.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1234.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1235.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1236.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1237.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1238.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1239.png
Creating...D:\College\Third Year\Computer Vision\cp2\Dataset

Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1319.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1320.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1321.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1322.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1323.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1324.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1325.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1326.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1327.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\Young\1328.png
Creating...D:\College\Third Year\Computer Vision\cp2\Dataset

In [4]:
#Gathering Testing Data
gabor(r"D:\College\Third Year\Computer Vision\cp2\Datasets\Common Dataset\Test\Adult", "Test\\Adult\\")

gabor(r"D:\College\Third Year\Computer Vision\cp2\Datasets\Common Dataset\Test\Old", "Test\\Old\\")

gabor(r"D:\College\Third Year\Computer Vision\cp2\Datasets\Common Dataset\Test\Young", "Test\\Young\\")


Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Adult\1.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Adult\2.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Adult\3.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Adult\4.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Adult\5.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Adult\6.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Adult\7.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Adult\8.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Adult\9.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Adult\10.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Adult\11.png
Creating

Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Adult\96.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Adult\97.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Adult\98.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Adult\99.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Adult\100.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Adult\101.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Adult\102.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Adult\103.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Adult\104.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Adult\105.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Adult\

Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Old\29.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Old\30.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Old\31.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Old\32.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Old\33.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Old\34.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Old\35.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Old\36.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Old\37.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Old\38.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Old\39.png
Creating...D:\College

Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\60.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\61.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\62.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\63.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\64.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\65.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\66.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\67.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\68.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\69.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\70.png

Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\157.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\158.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\159.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\160.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\161.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\162.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\163.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\164.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\165.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\166.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Yo

Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\255.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\256.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\257.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\258.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\259.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\260.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\261.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\262.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\263.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\264.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Yo

Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\349.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\350.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\351.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\352.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\353.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\354.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\355.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\356.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\357.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\358.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Yo

Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\441.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\442.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\443.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\444.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\445.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\446.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\447.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\448.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\449.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\450.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Yo

Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\540.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\541.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\542.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\543.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\544.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\545.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\546.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\547.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\548.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Young\549.png
Creating...D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Test\Yo

In [5]:
print(os.listdir(r"D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data"))

['Test', 'Train']


In [6]:
#Start by creating empty lists.
train_images = []
train_labels = [] 

In [7]:
for directory_path in glob.glob(r"D:\College\Third Year\Computer Vision\cp2\Datasets\Gabor Data\Train\*"):
    label = directory_path.split("\\")[-1]
    print(label)
    for img_path in glob.glob(os.path.join(directory_path, "*.png")):
        #print(img_path)
        img = cv2.imread(img_path, 0) #Reading color images
        img = cv2.resize(img, (300, 300)) #Resize images
        train_images.append(img.flatten())
        train_labels.append(label)

Adult
Old
Young


In [8]:
train_images = np.array(train_images)
train_labels = np.array(train_labels)

In [9]:
print(train_images)
print(train_labels)

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
['Adult' 'Adult' 'Adult' ... 'Young' 'Young' 'Young']


In [10]:
#Do exactly the same for test/validation images
# test
test_images = []
test_labels = []

In [11]:
for directory_path in glob.glob(r"D:\College\Third Year\Computer Vision\cp\Gabor Data\Test\*"):
    label = directory_path.split("\\")[-1]
    print(label)
    for img_path in glob.glob(os.path.join(directory_path, "*.png")):
        #print(img_path)
        img = cv2.imread(img_path, 0) #Reading color images
        img = cv2.resize(img, (300, 300)) #Resize images
        test_images.append(img.flatten())
        test_labels.append(label)

Adult
Old
Young


In [12]:
test_images = np.array(test_images)
test_labels = np.array(test_labels)

In [13]:
print(test_images)
print(test_labels)

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
['Adult' 'Adult' 'Adult' ... 'Young' 'Young' 'Young']


In [14]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(test_labels)
test_labels_encoded = le.transform(test_labels)

le.fit(train_labels)
train_labels_encoded = le.transform(train_labels)

In [15]:
print(le.transform(test_labels))

[0 0 0 ... 2 2 2]


In [16]:
#Split data into test and train datasets (already split but assigning to meaningful convention)
#If you only have one dataset then split here
x_train, y_train, x_test, y_test = train_images, train_labels_encoded, test_images, test_labels_encoded

In [17]:
#SVM Linear
svm_clf = svm.SVC()
svm_clf.fit(x_train, y_train)
y_pred1 = svm_clf.predict(x_test)
print("Accuracy:  \t\t"+str(metrics.accuracy_score(y_test, y_pred1)))
print('Balanced accuracy: \t', metrics.balanced_accuracy_score(y_test, y_pred1))
print('Precision accuracy: \t', metrics.precision_score(y_test, y_pred1,average='macro'))
print("Recall Score: \t\t",metrics.recall_score(y_test, y_pred1,average='weighted'))
print("F1 Score: \t\t",metrics.f1_score(y_test, y_pred1,average='micro'))
print('\nConfusion Matrix: \n',confusion_matrix(y_test, y_pred1))

Accuracy:  		0.8669767441860465
Balanced accuracy: 	 0.7761666666666667
Precision accuracy: 	 0.6707815072287371
Recall Score: 		 0.8669767441860465
F1 Score: 		 0.8669767441860465

Confusion Matrix: 
 [[  69    0   31]
 [   0   38   12]
 [ 234    9 1757]]


In [18]:
#Decision Tree Classifier
from sklearn.metrics import accuracy_score
#Assign model with Decision Tree classifier
model_dt = DecisionTreeClassifier(max_depth=13)
model_dt.fit(x_train, y_train)
joblib.dump(model_dt,"model_dt")

#predicting the traget variable using testing variables
y_pred1 = model_dt.predict(x_test)
#Results
print("Decision Tree Results")
print("Decision Tree Accuracy: ",accuracy_score(y_test, y_pred1)*100,"%")
print("Train Accuracy:",model_dt.score(x_train, y_train))
print("Test Accuracy:",model_dt.score(x_test, y_test))
print("Accuracy:  \t\t"+str(metrics.accuracy_score(y_test, y_pred1)))
print('Balanced accuracy: \t', metrics.balanced_accuracy_score(y_test, y_pred1))
print('Precision accuracy: \t', metrics.precision_score(y_test, y_pred1,average='macro'))
print("Recall Score: \t\t",metrics.recall_score(y_test, y_pred1,average='weighted'))
print("F1 Score: \t\t",metrics.f1_score(y_test, y_pred1,average='micro'))
print('\nConfusion Matrix: \n',confusion_matrix(y_test, y_pred1))


Decision Tree Results
Decision Tree Accuracy:  80.83720930232559 %
Train Accuracy: 0.9715053763440861
Test Accuracy: 0.8083720930232559
Accuracy:  		0.8083720930232559
Balanced accuracy: 	 0.733
Precision accuracy: 	 0.49930491331601123
Recall Score: 		 0.8083720930232559
F1 Score: 		 0.8083720930232559

Confusion Matrix: 
 [[  62    1   37]
 [   5   38    7]
 [ 293   69 1638]]


In [1]:
#Random Forest classifier
model_rf = RandomForestClassifier(n_estimators = 50)

model_rf.fit(x_train, y_train)
joblib.dump(model_rf,"model_rf")

y_pred2 = model_rf.predict(x_test)
print("Random Forest Clasifier")
print("Train Accuracy:",model_rf.score(x_train, y_train))
print("Test Accuracy:",model_rf.score(x_test, y_test))
print("Accuracy:  \t\t"+str(accuracy_score(y_test, y_pred2)))
print('Balanced accuracy: \t', metrics.balanced_accuracy_score(y_test, y_pred2))
print('Precision accuracy: \t', metrics.precision_score(y_test, y_pred2,average='macro'))
print("Recall Score: \t\t",metrics.recall_score(y_test, y_pred2,average='macro'))
print("F1 Score: \t\t",metrics.f1_score(y_test, y_pred2,average='micro'))
print('\nConfusion Matrix: \n',confusion_matrix(y_test, y_pred2))

NameError: name 'RandomForestClassifier' is not defined

In [20]:
#KNN classifier
model_knn = KNeighborsClassifier(n_neighbors = 5)
model_knn.fit(x_train, y_train)
#joblib.dump(model_knn,"model_knn")
y_pred3 = model_knn.predict(x_test)
print("KNN")
print("Train Accuracy:",model_knn.score(x_train, y_train))
print("Test Accuracy:",model_knn.score(x_test, y_test))
print("Accuracy:  \t\t"+str(accuracy_score(y_test, y_pred3)))
print('Balanced accuracy: \t', metrics.balanced_accuracy_score(y_test, y_pred3))
print('Precision accuracy: \t', metrics.precision_score(y_test, y_pred3,average='macro'))
print("Recall Score: \t\t",metrics.recall_score(y_test, y_pred3,average='weighted'))
print("F1 Score: \t\t",metrics.f1_score(y_test, y_pred3,average='micro'))
print('\nConfusion Matrix: \n',confusion_matrix(y_test, y_pred3))

C:\Users\omkar\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


KNN


C:\Users\omkar\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


Train Accuracy: 0.9758064516129032
Test Accuracy: 0.7344186046511628
Accuracy:  		0.7344186046511628
Balanced accuracy: 	 0.7223333333333334
Precision accuracy: 	 0.4338073503819288
Recall Score: 		 0.7344186046511628
F1 Score: 		 0.7344186046511628

Confusion Matrix: 
 [[  67    2   31]
 [   0   38   12]
 [ 257  269 1474]]


C:\Users\omkar\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [21]:
#xgboost classifier
model_xgboost = XGBClassifier().fit(x_train, y_train)
joblib.dump(model_xgboost,"model_xgboost")
y_pred5 = model_xgboost.predict(x_test)
print("XGboost")
print("Train Accuracy:",model_xgboost.score(x_train, y_train))
print("Test Accuracy:",model_xgboost.score(x_test, y_test))
print("Accuracy:  \t\t"+str(metrics.accuracy_score(y_test, y_pred5)))
print('Balanced accuracy: \t', metrics.balanced_accuracy_score(y_test, y_pred5))
print('Precision accuracy: \t', metrics.precision_score(y_test, y_pred5,average='macro'))
print("Recall Score: \t\t",metrics.recall_score(y_test, y_pred5,average='weighted'))
print("F1 Score: \t\t",metrics.f1_score(y_test, y_pred5,average='micro'))
print('\nConfusion Matrix: \n',confusion_matrix(y_test, y_pred5))

XGboost
Train Accuracy: 1.0
Test Accuracy: 0.8693023255813953
Accuracy:  		0.8693023255813953
Balanced accuracy: 	 0.7898333333333333
Precision accuracy: 	 0.6504564560780897
Recall Score: 		 0.8693023255813953
F1 Score: 		 0.8693023255813954

Confusion Matrix: 
 [[  71    0   29]
 [   2   39    9]
 [ 227   14 1759]]
